# Initialize Impresso Client

In this cell, we initialize the Impresso client to connect to the Impresso API. 
The `impresso` variable is an instance of `impresso.client.ImpressoClient`, which allows us to interact with the API 
and perform various operations such as searching for articles, retrieving article details, and fetching facets.

In [ ]:
from impresso import connect

impresso = connect()

## Search content items

In this notebook, we will search for content items that contain the term "European Union" in the text. The results are ordered by date.

Below the result container is rendered as an overview of what it contains.

In [28]:
result = impresso.search.find(
    term="European Union",
    order_by="date",
)
result

Below, we will search for a term "European Union" in the Impresso data.
Then we will use the `result` variable, to access and print titles of the first three articles returned by the search query.

The `pydantic` property is a [Pydantic](https://docs.pydantic.dev/latest/) model representing the response of the Impresso API. It provides a way to ensure that the data conforms to specified types and constraints, making it easier to work with structured data in a reliable and consistent manner.
We use the `data` property of the response to iterate over the page of the results and return titles of the articles that contain the search term.

In [29]:
result = impresso.search.find(
    term="European Union",
    order_by="date",
)
for content_item in result.pydantic.data[:3]:
    print(content_item.text.title)

None
None
Europäischer Föderalistenkongreß in Rom

There are several useful properties on the result object that let us know the total nubmer of results found, the current page and its size.

In [30]:
print("%i results were found for this term. The current result object contains %i items starting from the item number %i" % (result.total, result.size, result.offset))

93 results were found for this term. The current result object contains 93 items starting from the item number 0

### Pydantic
The full response from the Impresso API as a pydantic model.

In [31]:
result.pydantic

SearchResponseSchema(data=[ContentItem(id='AGMO-1818-12-06-a-i0015', issueId='AGMO-1818-12-06-a', relevanceScore=0.27428578022442446, meta=ContentItemMeta(sourceType='newspaper', sourceMedium='print', mediaId='AGMO', mediaTitle=None, date=datetime.datetime(1818, 12, 6, 0, 0, tzinfo=TzInfo(UTC)), partnerId='BL', partnerTitle='British Library', countryCode='UK', provinceCode='na'), text=ContentItemText(documentType='ci', itemType='ar', itemTypeLabel='Article', originalLangCode='en', langCode='en', contentLength=1664, snippet='bc 33, ritiob _Monitor. SUNDAY, DECEMBER 6, Isis. The news from the Cootinept received in the course of the last week, through the medium of the forei', title=None, content=None, matches=[ContentItemTextMatch(fragment=' is passing at this moment in the North. Did they never hear Of a society culled the Grand • .<em>European</em> <em>Union</em>', coords=None, pageId=None, iiif=None)]), semanticEnrichments=ContentItemSemanticEnrichments(ocrQuality=0.92, namedEntities=None, mentions=None, topics=[], collections=[], embeddings=None), image=ContentItemImage(pagesCount=1, isFrontPage=False, isCoordinatesConverted=None, pages=[ContentItemPage(id='AGMO-1818-12-06-a-p0005', number=5, regionCoordinates=[], iiif=None)], lineBreaks=None, paragraphBreaks=None, regionBreaks=None), audio=ContentItemAudio(startTime=None, duration=None, records=[], recordsCount=None), access=ContentItemAccessRights(dataDomain='pbl', dataDomainLabel='Public', copyright='pbl', copyrightLabel='Public domain', accessBitmaps=None)), ContentItem(id='MEXA-1848-04-08-a-i0105', issueId='MEXA-1848-04-08-a', relevanceScore=0.0909232501231457, meta=ContentItemMeta(sourceType='newspaper', sourceMedium='print', mediaId='MEXA', mediaTitle=None, date=datetime.datetime(1848, 4, 8, 0, 0, tzinfo=TzInfo(UTC)), partnerId='BL', partnerTitle='British Library', countryCode='UK', provinceCode='na'), text=ContentItemText(documentType='ci', itemType='ar', itemTypeLabel='Article', originalLangCode='en', langCode='en', contentLength=7601, snippet='SUPPLEMENT TO THE MANCHESTER EXAMINER, SATURDAY, APRIL 8, 1848. distinctions in society, which prevent the highest progress and improvement of all. On', title=None, content=None, matches=[ContentItemTextMatch(fragment=' policy, and yet be prohibited by the unalterable code of the great <em>European</em> <em>union</em> from ever entering', coords=None, pageId=None, iiif=None)]), semanticEnrichments=ContentItemSemanticEnrichments(ocrQuality=0.97, namedEntities=None, mentions=None, topics=[], collections=[], embeddings=None), image=ContentItemImage(pagesCount=1, isFrontPage=False, isCoordinatesConverted=None, pages=[ContentItemPage(id='MEXA-1848-04-08-a-p0010', number=10, regionCoordinates=[], iiif=None)], lineBreaks=None, paragraphBreaks=None, regionBreaks=None), audio=ContentItemAudio(startTime=None, duration=None, records=[], recordsCount=None), access=ContentItemAccessRights(dataDomain='pbl', dataDomainLabel='Public', copyright='pbl', copyrightLabel='Public domain', accessBitmaps=None)), ContentItem(id='luxwort-1948-11-25-a-i0033', issueId='luxwort-1948-11-25-a', relevanceScore=0.6320811441767413, meta=ContentItemMeta(sourceType='newspaper', sourceMedium='print', mediaId='luxwort', mediaTitle='Luxemburger Wort', date=datetime.datetime(1948, 11, 25, 0, 0, tzinfo=TzInfo(UTC)), partnerId='BNL', partnerTitle='National Library of Luxembourg', countryCode='LU', provinceCode='na'), text=ContentItemText(documentType='ci', itemType='ar', itemTypeLabel='Article', originalLangCode='de', langCode='de', contentLength=733, snippet='Europäischer Föderalistenkongreß in Rom (Schluss) Interessant war auch die Resolution der Sous-co m mission Syndicale, wie überhaupt die rege Beteilig', title='Europäischer Föderalistenkongreß in Rom', content=None, matches=[ContentItemTextMatch(fragment=' <em>European</em> <em>Union</em> und mit den Parliamentary Federalist Groups vor, um den augenblicklichen Widerstand', coords=None, pageId=None, iiif=None)]), semanticEnrichments=ContentItemSemanticEnrichments(ocrQuality=0.97, namedEntities=NamedEntities(persons=[ContentItemNamedEntity(id='2-50-Pius_XII.', count=1, label='Pius XII.')], locations=[], organisations=[], newsagencies=[]), mentions=Mentions(persons=[ContentItemMention(surfaceForm='Papst Pius XII', mentionConfidence=95.88, startOffset=None, endOffset=None)], locations=[], organisations=[], newsagencies=[]), topics=[ContentItemTopic(relevance=0.202, id='tm-de-all-v2.0_tp25_de', label='wirtschaft · entwicklung · industrie · arbeit · frage', languageCode='de'), ContentItemTopic(relevance=0.16, id='tm-de-all-v2.0_tp52_de', label='regierung · paris · konferenz · frankreich · frage', languageCode='de'), ContentItemTopic(relevance=0.157, id='tm-de-all-v2.0_tp86_de', label=None, languageCode=None), ContentItemTopic(relevance=0.112, id='tm-de-all-v2.0_tp14_de', label='kirche · papst · bischof · pfarrer · predigt', languageCode='de'), ContentItemTopic(relevance=0.112, id='tm-de-all-v2.0_tp77_de', label=None, languageCode=None), ContentItemTopic(relevance=0.096, id='tm-de-all-v2.0_tp95_de', label='krieg · deutschland · frankreich · welt · friede', languageCode='de'), ContentItemTopic(relevance=0.057, id='tm-de-all-v2.0_tp24_de', label='könig · kaiser · königin · prinz · prinzessin', languageCode='de')], collections=[], embeddings=None), image=ContentItemImage(pagesCount=1, isFrontPage=False, isCoordinatesConverted=None, pages=[ContentItemPage(id='luxwort-1948-11-25-a-p0006', number=6, regionCoordinates=[], iiif=ContentItemPageIIIF(manifestUrl=Url('https://iiif.eluxemburgensia.lu/image/iiif/2/ark:70795%2fhg7djq%2fpages%2f6/info.json'), thumbnailUrl=Url('https://iiif.eluxemburgensia.lu/image/iiif/2/ark:70795%2fhg7djq%2fpages%2f6/full/150,/0/default.png')))], lineBreaks=None, paragraphBreaks=None, regionBreaks=None), audio=ContentItemAudio(startTime=None, duration=None, records=[], recordsCount=None), access=ContentItemAccessRights(dataDomain='prt', dataDomainLabel='Private', copyright='in_cpy', copyrightLabel='Protected domain: in copyright', accessBitmaps=None)), ContentItem(id='FZG-1950-06-17-a-i0045', issueId='FZG-1950-06-17-a', relevanceScore=0.5263839304066368, meta=ContentItemMeta(sourceType='newspaper', sourceMedium='print', mediaId='FZG', mediaTitle='Freiburger Nachrichten', date=datetime.datetime(1950, 6, 17, 0, 0, tzinfo=TzInfo(UTC)), partnerId='SNL', partnerTitle='Swiss National Library', countryCode='CH', provinceCode='FR'), text=ContentItemText(documentType='ci', itemType='ar', itemTypeLabel='Article', originalLangCode=None, langCode='de', contentLength=1200, snippet='Um EJnropa herum Die Furcht vor Krieg und Vernichtung hält | Sinn haben, dann heißt dies alles: 1. Daß für « iie Lebewesen, die der Herrgott mit Vernu', title='Um EJnropa herum Die Furcht vor Krieg un...', content=None, matches=[ContentItemTextMatch(fragment=' Erklärung der Exekutive der Labourpartei, die den Titel « <em>European</em> <em>Union</em> » trägt. Vor 10 Jahren hat England', coords=None, pageId=None, iiif=None)]), semanticEnrichments=ContentItemSemanticEnrichments(ocrQuality=0.97, namedEntities=NamedEntities(persons=[ContentItemNamedEntity(id='2-50-Konrad_Adenauer', count=1, label='Konrad Adenauer'), ContentItemNamedEntity(id='2-50-Georges_Bidault', count=1, label='Georges Bidault')], locations=[], organisations=[], newsagencies=[]), mentions=Mentions(persons=[ContentItemMention(surfaceForm='Adenauer', mentionConfidence=96.75, startOffset=None, endOffset=None), ContentItemMention(surfaceForm='Bidault', mentionConfidence=89.71, startOffset=None, endOffset=None)], locations=[], organisations=[], newsagencies=[]), topics=[ContentItemTopic(relevance=0.265, id='tm-de-all-v2.0_tp86_de', label=None, languageCode=None), ContentItemTopic(relevance=0.181, id='tm-de-all-v2.0_tp95_de', label='krieg · deutschland · frankreich · welt · friede', languageCode='de'), ContentItemTopic(relevance=0.154, id='tm-de-all-v2.0_tp77_de', label=None, languageCode=None), ContentItemTopic(relevance=0.09, id='tm-de-all-v2.0_tp41_de', label='london · england · sir · lord · regierung', languageCode='de'), ContentItemTopic(relevance=0.08, id='tm-de-all-v2.0_tp79_de', label='don · and · min · sage · uli', languageCode='de')], collections=[], embeddings=None), image=ContentItemImage(pagesCount=1, isFrontPage=True, isCoordinatesConverted=None, pages=[ContentItemPage(id='FZG-1950-06-17-a-p0001', number=1, regionCoordinates=[], iiif=ContentItemPageIIIF(manifestUrl=Url('https://dev.impresso-project.ch/media/iiif/FZG-1950-06-17-a-p0001/info.json'), thumbnailUrl=Url('https://dev.impresso-project.ch/media/iiif/FZG-1950-06-17-a-p0001/full/150,/0/default.png')))], lineBreaks=None, paragraphBreaks=None, regionBreaks=None), audio=ContentItemAudio(startTime=None, duration=None, records=[], recordsCount=None), access=ContentItemAccessRights(dataDomain='prt', dataDomainLabel='Private', copyright='in_cpy', copyrightLabel='Protected domain: in copyright', accessBitmaps=None)), ContentItem(id='JDG-1954-11-03-a-i0032', issueId='JDG-1954-11-03-a', relevanceScore=0.4800735772976317, meta=ContentItemMeta(sourceType='newspaper', sourceMedium='print', mediaId='JDG', mediaTitle='Journal de Genève', date=datetime.datetime(1954, 11, 3, 0, 0, tzinfo=TzInfo(UTC)), partnerId='SNL', partnerTitle='Swiss National Library', countryCode='CH', provinceCode='VD'), text=ContentItemText(documentType='ci', itemType='ar', itemTypeLabel='Article', originalLangCode='fr', langCode='fr', contentLength=717, snippet='Washington et les négociations avec Moscou (De notre correspondant) II y a du neuf à Washington. Un silence presque digne a remplacé ce que M. Adlai S', title='Washington et les négociations avec Moscou', content=None, matches=[ContentItemTextMatch(fragment=' (sans distinction de partis) sont en place aux deux bouts du monde libre avec la WEU (Western <em>European</em> <em>Union</em>', coords=None, pageId=None, iiif=None)]), semanticEnrichments=ContentItemSemanticEnrichments(ocrQuality=0.99, namedEntities=NamedEntities(persons=[ContentItemNamedEntity(id='2-50-Anthony_Eden', count=1, label='Anthony Eden'), ContentItemNamedEntity(id='2-50-Dwight_D._Eisenhower', count=1, label='Dwight D. Eisenhower'), ContentItemNamedEntity(id='2-50-John_Foster_Dulles', count=1, label='John Foster Dulles'), ContentItemNamedEntity(id='2-50-Konrad_Adenauer', count=1, label='Konrad Adenauer'), ContentItemNamedEntity(id='2-50-Pierre_Mendès_France', count=1, label='Pierre Mendès France')], locations=[ContentItemNamedEntity(id='2-54-Moscou', count=1, label='Moscou'), ContentItemNamedEntity(id='2-54-Viêt_Nam', count=1, label='Viêt Nam'), ContentItemNamedEntity(id='2-54-Chine', count=1, label='Chine'), ContentItemNamedEntity(id='2-54-Pékin', count=1, label='Pékin'), ContentItemNamedEntity(id='2-54-Allemagne', count=1, label='Allemagne'), ContentItemNamedEntity(id='2-54-États-Unis', count=1, label='États-Unis')], organisations=[ContentItemNamedEntity(id='2-53-États-Unis', count=1, label='États-Unis'), ContentItemNamedEntity(id='2-53-Communauté_européenne_de_défense', count=1, label='Communauté européenne de défense'), ContentItemNamedEntity(id='2-53-Union_des_républiques_socialistes_soviétiques', count=1, label='Union des républiques socialistes soviétiques')], newsagencies=[]), mentions=Mentions(persons=[ContentItemMention(surfaceForm='sir Anthony Eden', mentionConfidence=98.08, startOffset=None, endOffset=None), ContentItemMention(surfaceForm='Eisenhower', mentionConfidence=66.87, startOffset=None, endOffset=None), ContentItemMention(surfaceForm='Dulles', mentionConfidence=83.59, startOffset=None, endOffset=None), ContentItemMention(surfaceForm='Adenauer', mentionConfidence=94.02, startOffset=None, endOffset=None), ContentItemMention(surfaceForm='Mendès', mentionConfidence=91.23, startOffset=None, endOffset=None)], locations=[ContentItemMention(surfaceForm='Moscou', mentionConfidence=98.27, startOffset=None, endOffset=None), ContentItemMention(surfaceForm='Vietnam', mentionConfidence=96.1, startOffset=None, endOffset=None), ContentItemMention(surfaceForm='Formose', mentionConfidence=98.27, startOffset=None, endOffset=None), ContentItemMention(surfaceForm='Chine', mentionConfidence=90.46, startOffset=None, endOffset=None), ContentItemMention(surfaceForm='Pékin', mentionConfidence=98.39, startOffset=None, endOffset=None), ContentItemMention(surfaceForm='Allemagne', mentionConfidence=95.77, startOffset=None, endOffset=None), ContentItemMention(surfaceForm='Amérique', mentionConfidence=92.28, startOffset=None, endOffset=None)], organisations=[ContentItemMention(surfaceForm='Assemblée des Nations Unies', mentionConfidence=93.84, startOffset=None, endOffset=None), ContentItemMention(surfaceForm='WEU', mentionConfidence=78.4, startOffset=None, endOffset=None), ContentItemMention(surfaceForm='Western European Union', mentionConfidence=89.25, startOffset=None, endOffset=None), ContentItemMention(surfaceForm='Etats', mentionConfidence=79.22, startOffset=None, endOffset=None), ContentItemMention(surfaceForm='CED', mentionConfidence=74.36, startOffset=None, endOffset=None), ContentItemMention(surfaceForm='Union soviétique', mentionConfidence=89.98, startOffset=None, endOffset=None)], newsagencies=[]), topics=[ContentItemTopic(relevance=0.253, id='tm-fr-all-v2.0_tp29_fr', label='guerre · paix · pays · peuple · politique', languageCode='fr'), ContentItemTopic(relevance=0.1, id='tm-fr-all-v2.0_tp44_fr', label='temps · argent · gens · foi · chose', languageCode='fr'), ContentItemTopic(relevance=0.098, id='tm-fr-all-v2.0_tp03_fr', label='gouvernement · conférence · accord · question · traité', languageCode='fr'), ContentItemTopic(relevance=0.096, id='tm-fr-all-v2.0_tp25_fr', label='journal · monde · vie · direct · série', languageCode='fr'), ContentItemTopic(relevance=0.082, id='tm-fr-all-v2.0_tp36_fr', label='main · tête · temps · coup · air', languageCode='fr'), ContentItemTopic(relevance=0.053, id='tm-fr-all-v2.0_tp00_fr', label='pays · foi · cours · part · dune', languageCode='fr')], collections=[], embeddings=None), image=ContentItemImage(pagesCount=1, isFrontPage=False, isCoordinatesConverted=None, pages=[ContentItemPage(id='JDG-1954-11-03-a-p0003', number=3, regionCoordinates=[], iiif=ContentItemPageIIIF(manifestUrl=Url('https://dev.impresso-project.ch/media/iiif/JDG-1954-11-03-a-p0003/info.json'), thumbnailUrl=Url('https://dev.impresso-project.ch/media/iiif/JDG-1954-11-03-a-p0003/full/150,/0/default.png')))], lineBreaks=None, paragraphBreaks=None, regionBreaks=None), audio=ContentItemAudio(startTime=None, duration=None, records=[], recordsCount=None), access=ContentItemAccessRights(dataDomain='prt', dataDomainLabel='Private', copyright='in_cpy', copyrightLabel='Protected domain: in copyright', accessBitmaps=None)), ContentItem(id='JDG-1954-11-27-a-i0041', issueId='JDG-1954-11-27-a', relevanceScore=0.4047019080911228, meta=ContentItemMeta(sourceType='newspaper', sourceMedium='print', mediaId='JDG', mediaTitle='Journal de Genève', date=datetime.datetime(1954, 11, 27, 0, 0, tzinfo=TzInfo(UTC)), partnerId='SNL', partnerTitle='Swiss National Library', countryCode='CH', provinceCode='VD'), text=ContentItemText(documentType='ci', itemType='ar', itemTypeLabel='Article', originalLangCode='fr', langCode='fr', contentLength=783, snippet='AH, CES INITIALES ! Pour répondre à la demande de nombreux lecteurs, nous donnons ci-dessous la liste des principales organisations internationales gé', title='AH, CES INITIALES !', content=None, matches=[ContentItemTextMatch(fragment=" Centre'OEEC : Organisation for European Economie Coopération. : WEU : Western <em>European</em> <em>Union</em> EPU : European", coords=None, pageId=None, iiif=None)]), semanticEnrichments=ContentItemSemanticEnrichments(ocrQuality=0.93, namedEntities=NamedEntities(persons=[], locations=[ContentItemNamedEntity(id='2-54-Asie', count=1, label='Asie'), ContentItemNamedEntity(id='2-54-Extrême-Orient', count=1, label='Extrême-Orient'), ContentItemNamedEntity(id='2-54-Corée', count=1, label='Corée'), ContentItemNamedEntity(id='2-54-Proche-Orient', count=1, label='Proche-Orient'), ContentItemNamedEntity(id='2-54-Korea', count=1, label='Korea'), ContentItemNamedEntity(id='2-54-Europe', count=1, label='Europe'), ContentItemNamedEntity(id='2-54-Australie', count=2, label='Australie'), ContentItemNamedEntity(id='2-54-États-Unis', count=1, label='États-Unis'), ContentItemNamedEntity(id='2-54-Londres', count=1, label='Londres'), ContentItemNamedEntity(id='2-54-Paris', count=1, label='Paris')], organisations=[ContentItemNamedEntity(id='2-53-Organisation_des_Nations_unies', count=1, label='Organisation des Nations unies'), ContentItemNamedEntity(id='2-53-Amérique_latine', count=1, label='Amérique latine'), ContentItemNamedEntity(id='2-53-Conseil_économique_et_social_des_Nations_unies', count=2, label='Conseil économique et social des Nations unies'), ContentItemNamedEntity(id='2-53-Organisation_internationale_du_travail', count=1, label='Organisation internationale du travail'), ContentItemNamedEntity(id='2-53-Union_internationale_des_télécommunications', count=1, label='Union internationale des télécommunications'), ContentItemNamedEntity(id='2-53-Science', count=1, label='Science'), ContentItemNamedEntity(id='2-53-Union_postale_universelle', count=2, label='Union postale universelle'), ContentItemNamedEntity(id='2-53-Banque_mondiale', count=1, label='Banque mondiale'), ContentItemNamedEntity(id="2-53-Organisation_de_l'aviation_civile_internationale", count=1, label="Organisation de l'aviation civile internationale"), ContentItemNamedEntity(id='2-53-International_Labour_Organization', count=1, label='International Labour Organization'), ContentItemNamedEntity(id='2-53-World_Meteorological_Organization', count=2, label='World Meteorological Organization'), ContentItemNamedEntity(id="2-53-Organisation_des_Nations_unies_pour_l'éducation,_la_science_et_la_culture", count=1, label="Organisation des Nations unies pour l'éducation, la science et la culture"), ContentItemNamedEntity(id='2-53-Accord_général_sur_les_tarifs_douaniers_et_le_commerce', count=1, label='Accord général sur les tarifs douaniers et le commerce'), ContentItemNamedEntity(id='2-53-Océan_Atlantique', count=1, label='Océan Atlantique'), ContentItemNamedEntity(id="2-53-Organisation_du_traité_de_l'Atlantique_nord", count=1, label="Organisation du traité de l'Atlantique nord"), ContentItemNamedEntity(id='2-53-Organisation_européenne_pour_la_recherche_nucléaire', count=1, label='Organisation européenne pour la recherche nucléaire'), ContentItemNamedEntity(id="2-53-Union_de_l'Europe_occidentale", count=2, label="Union de l'Europe occidentale"), ContentItemNamedEntity(id='2-53-Communauté_européenne_de_défense', count=1, label='Communauté européenne de défense'), ContentItemNamedEntity(id='2-53-Union_européenne_des_paiements', count=2, label='Union européenne des paiements'), ContentItemNamedEntity(id='2-53-World_Federation_of_Trade_Unions', count=1, label='World Federation of Trade Unions')], newsagencies=[]), mentions=Mentions(persons=[ContentItemMention(surfaceForm='Puissances', mentionConfidence=56.91, startOffset=None, endOffset=None), ContentItemMention(surfaceForm='SACEUR', mentionConfidence=34.42, startOffset=None, endOffset=None), ContentItemMention(surfaceForm='Commandant en chef allié en Europe', mentionConfidence=73.31, startOffset=None, endOffset=None), ContentItemMention(surfaceForm='général Gruenther', mentionConfidence=94.62, startOffset=None, endOffset=None), ContentItemMention(surfaceForm='Commandant en chef des forces navales atlantiques', mentionConfidence=79.31, startOffset=None, endOffset=None), ContentItemMention(surfaceForm='CINCAFMED', mentionConfidence=46.41, startOffset=None, endOffset=None), ContentItemMention(surfaceForm='Commandant en chef en terranée NATO', mentionConfidence=70.08, startOffset=None, endOffset=None), ContentItemMention(surfaceForm='Commander in Chief', mentionConfidence=62

### Pandas
We can also get the search results as a [Pandas](https://pandas.pydata.org/) DataFrame. 
This allows us to easily manipulate and analyze the data using pandas' powerful data manipulation capabilities.

In [32]:
df = result.df
df.head(2)

,issueId,relevanceScore,meta.sourceType,meta.sourceMedium,meta.date,meta.mediaId,meta.partnerId,meta.partnerTitle,meta.countryCode,meta.provinceCode,...,meta.mediaTitle,text.title,semanticEnrichments.namedEntities.persons,semanticEnrichments.namedEntities.locations,semanticEnrichments.namedEntities.organisations,semanticEnrichments.namedEntities.newsagencies,semanticEnrichments.mentions.persons,semanticEnrichments.mentions.locations,semanticEnrichments.mentions.organisations,semanticEnrichments.mentions.newsagencies
id,,,,,,,,,,,,,,,,,,,,,
AGMO-1818-12-06-a-i0015,AGMO-1818-12-06-a,0.274286,newspaper,print,1818-12-06T00:00:00+00:00,AGMO,BL,British Library,UK,na,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
MEXA-1848-04-08-a-i0105,MEXA-1848-04-08-a,0.090923,newspaper,print,1848-04-08T00:00:00+00:00,MEXA,BL,British Library,UK,na,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Get a content item

Below we will use the `content_items` resource to get an article by its ID:

In [33]:
content_item = impresso.content_items.get("NZZ-1794-08-09-a-i0002")
content_item

We can also get it as a Pydantic model or as a DataFrame.

In [34]:
content_item.pydantic.text.content if content_item.pydantic.text else "No text content available"

'^chutch schleunige Vorkehrungen der bewafnetenNazi «» « ulmacht versichert. unV t >;.. 3 >; Stadthaus auf n...!)..,. zlVbereyiere wit sc! i! enAn. b >; wgsri! sich befand, mm \'. ügcn l » ssl ». Während der N « chi cischlcncndie vnser,«\'?.«.» \'NißliNererwaliungen i » P.. ric vor een,.« eum »., um »« lftlven il », cr Anbanglichteitzu veillcl\'ern. Gegen ren Älprgen <;» ml >; t dae Stadthaus erode. <;. leda »! ermordete \'Dh selbK. D >; e beyden Roberepiere versuchten ras glci- H ». D, r\'ältere schoß sich einen Theil de >;>; Gesichte hincks, jlnv rer jüngere stürz « sich aue dem Fenster. und Herbräch b <; yde Beine. Dcr ältere wu » de.. ufeiner Trag » , dnhrevortenKonvcntssaal geblecht, abermal. e. lMdt » erpicht, ihn herumzutragen. Hm ic,. Lhenmder (2z. Iich) Abends wurden beyde Roberepiere, Couthon, der . Migadcgeneral Lavalelce, Hanriot, Hominandont der Marter Nazionalgarde, Dümas, Präsident des Nevolu » Hsd »« ribnnals, St. Iuft, Payän Nazivna!» Aa « nt » n der \'Komüne ven Paris, Vivier, Präsident oer Iatobmer » <; vel sammlung. Gobiau, Substitut des öffentlich, n Anklägers. Fltmiüt. chaire von Paris, ne.\' st n Nunizi- \'Palräihtn hingerichtet. vÄn dm zwey folgenden Tagen \'. darauf trafdasgleichc-Schickftl z; andere Glieder des \'Homünenra. hs. Iin Moniteur wird Robitspieres un, d seiner Miischuldigen Hinrichtung mit folgenden Refic « Dienen btglett. t:.» Möge sich hieran jeder spiegeln, der \'es inekünftigwagenftllte, d! eNazl0nalsoitveräl!.! tät zu ^mißbrauchen! Glorwürdign Tag, herauf einmal alle . Hofnungen derVoa. ißetttn vereicelthat! Diese rechne » ^fen darauf, daß Ie init emein Niktateur kapitülier «\'« könnten, jllbu, nein! Sie Wen, keine » anbew Ditta, . tfurÄls tli. s sfanzMche Volt haben, u » d vq » diesti » . habe,, fif weder Medtu ». och Wassensi. Nstand Fu \'hoffe,,. Was für ein erhabenes Schauspiel ist, nicht die Anergische Emnlüthigkeit des Konvents! Wie Mr mG sen 7die Hgioteurs zittern, » enn sie sehern wie festen Schrilles das Pariservolk gehe » und wie willig sich alle Bürger « ui den Konvent herum versiimmeln! Dies « Revoluzien giebt deni Konvent eine neue Stäck, aber H auch zugleich das Todesurtheil\'für alle diejenigen, die es wagtn » iKchten, ihn zu trennen oder ben. bzu. pi\'n-, pigen. Vergebens werden sich. die unaufhkrlichen Verläumder dc « volkes dieser neuen Ereignisse als einerGe\'lsgcnheit bedienen können, dassel. be der Wetferw^ndig « keit zu beschuleigen. Das Volk ist ste «. niemen Uilhei- Ungerecht. Es will die Freyheit, und liebt nur jene, dj « diese vertheidigen. Ke weniger es Individuen «« bechet, je standhafter wird es. t >; as Vaterland\'lieben. Ie wetng. r Individuen in Ansehn stehen,, je / mehr wird sich die if » ftntliche Freyheit befestigen. Wer so mMtig witd, daß er » en Versuch wagen kann, sich üb « Vie Gesetze hinweg Zusetzen, muß in jedem Bürger einen Plutus finden. Ner zu grosse Einfluß eilifs einzeln Menschen ist rie ge » sährl. chfte Plage für eine Republik.« Me wschtWtn Verznberungen, die als « ine Folge dieser ErHitgnW « lkgeseh «, werden kinnen, \'bestehen dKlim,, daß das Revo « luz! lmttib: ii!.. l ganz iü,! e ftNi. ver e, h^lt, so wie auch die Hell? c\'o,!!!!,! sjl! 0i! durch!>; i. « ü. ger Brennd, Eschas « se. i >; iu ten, Urc. n, laioi, Tburicc. Trcillard und- Taille « . ergänz! wol den ist.) Nl >;! m. si <; a msch » lle Mon... fn, jcre HoUlMls. dn 4ieThc, l,, eu oc «\' ezt werdcn. Sanlerre, wtlche Ülovriepitx m Vn d^. ft netznun ließ, wurde durch oi,« vereinigicn Hello-, und Gicht. hutktom. msi. c\'ne!. in Frey » heit\'gcftzt. ei scl ic » oer demKonvem. und vuMng » te, ale Ko, pora! otc ». a ^gemeiner Soldat angcftellt zu werten. In Bezi5hui. gHUf die ^ffentüct\'en Hinrich « lungen trat Tallien « ic einer wlchligen Beschuldigung gegen Robel kpicr « nus. ss hätten sich nämlich, sagte er, versch! tdt.! e teuce al » Gefangene in dieMrestebü. t «\' ser eingc^Iicheu \', deren Geschaft einzig barmn best «»-den würe, über die vorhandenen Gefangenen gewisse Men zu verfertigen, und Mm Vei. rainen, den » Ro « »« spiere zuliefern, weicher dann jedesmal diejenige?, welche ihn, am MfählliMcn-geschienen hätten, dem Revoluzione. nbunale zur Hinrichtung empfehlen Habe. Ndrva «««. Aus Anlwefpcn schreibt der Volts «» . vrästntant Richmd unterm 9. Thcrniidor s 27. Iul.) Fol » gendesan die Heilefdmmisston: « Ich berichte euch^ daß der Feind das Fort Lillogeräumt habe. DieTruppen der lXepublit sind gestern dort eingerückt. Die Englander shaven, als sie abzogen, an dem linken Ufer die Dämme ^durchbrochen, und dastand ^Meilen im Umfange un « terWaffer gesezt. Die beschädigten Einwohn er verwün- \'fchen sie. Sie sind ilber HalS und Hopf davon geficchen. ^Unsere leichten Truppen sind ihnen mehr als io Meilen auf die Spür gegangen, che sie ihre Avantgarde ens « deckten. Ee scheint, fie ziehen sich unter dieKanonenDra . Breda uno Nerg \'. ep\'Zovm. liessen si. IAntwerpen uns; 8 Kanonen zurück. Doit haben wir « uch ansehn » liche Magazine, besonders von Haber gefunden, von welchen gegen Säcke vorhanden seyn können. Mehr als zoo Privatleute baben Sachen an sich genommen, die der feindlichen Armee gehörten. Ich und laurent sin » jezt beschäft »\';«, die nöthigcn\'Untersuchungen anzustellen, und dasjenige, was wir finden, für die Republik... Beschlag zu nehmen.« Der D. visionc\'gn. eral Elnsuf meldet aus seinem Hauptquartier z « Warem unterm 9. Tb^lmiidor s 27. Iul) Nachstehendes an die Heilskonmussion: n DieSiimb «« und Maaßärwee hat diesen Morgen sich in Bewegung gesezt,\' in der Absicht, den Fcmd immer näher gegen Mastricht hin zu träng m, ihn über die Maaß zum Rückzug zu nöthigen, und M von Mlich Meister zu machen. Die^lvantMrde mai >; schittte an lie I « ar, der linke Flügel lehnte sick an Älentt. gl «\' und der rechte an St. Nikolas. Derselbe igriffdie veslüttich befindlichen Stellungen d,!» ^eindtl. an, der z^ar einige Zeit unserm Kanonenfeuer wider » stund! aber endlich, alsuMre Truppen mit bem Bätc!» "« t eindrängln, » ie Flilcht ergreife » «. ußte. Mrto^l »'

In [35]:
content_item.df[['id', 'meta.countryCode', 'text.langCode']]

                       id meta.countryCode text.langCode
0  NZZ-1794-08-09-a-i0002               CH            de

## Search facets

In this cell, we will search for facets related to the term "fromage" in the Impresso collection. This is a convenient way to see a breakdown of the search results by country.

In [36]:
country_facet = impresso.search.facet("country", term="fromage")
country_facet.df

        count
value
CH     197800
FR      33993
LU       7478
UK          6